Issue#7
janniklasrose/RWcDTI pull request #8
Opened 2021-02-05 17:06 UTC by ignasiialemany

Fix #7

2021-02-06 09:23 UTC, ignasiialemany commented
Still draft, still investigating one issue

2021-02-06 09:45 UTC, janniklasrose requested changes
Added some feedback. I think it's better to use a char array `'xyz'` for `Substrate.dim` so that we can specify which dimensions to operate on - `'yz'` will perform the random walk on the yz-plane

2021-02-06 09:45 UTC, janniklasrose commented on +MonteCarlo/@ParticleWalker/private/getLimitedStep.m
> +    dxdydz(1:dim) = getStep(dim, varargin{:});
`dxdydz(mask) = getStep(sum(mask), varargin{:});`

2021-02-06 09:45 UTC, janniklasrose commented on +Substrate/@Substrate/Substrate.m
> +	dim = 3
Change to `dim = 'xyz'`. Also, this is not indented correctly (at least when viewed on GitHub). Maybe you need to use spaces, not tabs

2021-02-06 09:45 UTC, janniklasrose commented on config/substrate.yml
> +  dimension: 1
The example shouldn't use non-default parameters, so instead of 1D specify `dimension: 'xyz'` (just `xyz` should also work since it is YAML)

2021-02-06 09:45 UTC, janniklasrose commented on +MonteCarlo/@ParticleWalker/private/getLimitedStep.m
> +dxdydz = zeros(1, 3);
add `mask = contains({'x', 'y', 'z'}, cellstr(dim.'));` to compute the [x, y, z] mask from `'xyz'` string `dim`

2021-02-07 19:15 UTC, janniklasrose approved these changes
Happy to merge

2021-02-07 19:15 UTC, janniklasrose commented on +MonteCarlo/@ParticleWalker/private/getLimitedStep.m
> +    mask = contains({'x', 'y', 'z'}, cellstr(dim.'));
Re-calculating the mask here inside the while loop isn't optimal, but I'm fine with leaving it for now. Maybe (eventually) move this outside the getLimitedStep altogether into `Substrate`:

```matlab
methods
  function obj = set.mask(obj, dim)
    if ischar(dim)
        obj.mask = contains({'x', 'y', 'z'}, cellstr(dim.'));
    else % assume correct input format
        obj.mask = dim;
  end
end
```

2021-02-08 11:51 UTC, ignasiialemany commented on +MonteCarlo/@ParticleWalker/private/getLimitedStep.m
> +    mask = contains({'x', 'y', 'z'}, cellstr(dim.'));
Yeah , definetly! I will add it into the class

2021-02-08 12:44 UTC, merged